name: ETL Pipeline CI

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Python syntax
        run: |
          python -m py_compile dags/*.py

      - name: Docker Compose Build
        run: |
          docker compose build

      # - name: Run tests
      #   run: |
      #     pytest